=== H2020-IPM-Decisions/WeatherService/src/main/resources/weatherDataSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Weather Data",
  "type": "object",
  "additionalProperties": false,
  "description": "Version 0.1. The schema describes the weather data format for the IPM Decisions platform. See an example here: https://ipmdecisions.nibio.no/api/wx/rest/weatheradapter/yr/?longitude=14.3711&latitude=67.2828&altitude=70",
  "$id": "https://ipmdecisions.nibio.no/api/wx/rest/schema/weatherdata",
  "properties": {
    "timeStart": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of the first weather observation. Format: \"yyyy-MM-dd'T'HH:mm:ssXXX\", e.g. 2020-04-09T18:00:00+02:00",
      "title": "Time start (yyyy-MM-dd'T'HH:mm:ssXXX)"
    },
    "timeEnd": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of the last weather observation. Format: \"yyyy-MM-dd'T'HH:mm:ssXXX\", e.g. 2020-04-09T18:00:00+02:00",
      "title": "Time end (yyyy-MM-dd'T'HH:mm:ssXXX)"
    },
    "interval": {
      "type": "integer",
      "description": "The sampling frequency in seconds. E.g. 3600 = hourly values",
      "title": "Sampling frequency (seconds)"
    },
    "weatherParameters": {
      "type": "array",
      "minItems": 1,
      "maxItems": 2147483647,
      "items": {
        "type": "integer"
      },
      "description": "The weather parameters. For reference, see https://ipmdecisions.nibio.no/api/wx/rest/parameter",
      "title": "Weather parameters"
    },
    "locationWeatherData": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/LocationWeatherData"
          }
        }
      ],
      "description": "The weather data per location.",
      "title": "Weather data"
    },
    "qc": {
      "oneOf": [
        {
          "type": "null",
          "title": "Not included"
        },
        {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      ]
    }
  },
  "required": [
    "timeStart",
    "timeEnd",
    "interval",
    "weatherParameters"
  ],
  "definitions": {
    "LocationWeatherData": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "longitude": {
          "type": "number",
          "description": "The longitude of the location. Decimal degrees (WGS84)",
          "title": "Longitude (WGS84)"
        },
        "latitude": {
          "type": "number",
          "description": "The latitude of the location. Decimal degrees (WGS84)",
          "title": "Latitude (WGS84)"
        },
        "altitude": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "number"
            }
          ],
          "description": "The altitude of the location. Measured in meters",
          "title": "Altitude (Meters)"
        },
        "data": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included."
            },
            {
              "type": "array",
              "items": {
                "type": "array",
                "items": {
                  "anyOf":[
                    {"type":"number"},
                    {"type":"null"}
                  ]
                }
              }
            }
          ],
          "description": "The data. In rows, ordered chronologically. Columns ordered as given in weatherParameters.",
          "title": "Weather data per location"
        },
        "length": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "integer"
            }
          ]
        },
        "width": {
          "oneOf": [
            {
              "type": "null",
              "title": "Not included"
            },
            {
              "type": "integer"
            }
          ]
        }
      },
      "required": [
        "longitude",
        "latitude"
      ]
    }
  }
}

=== H2020-IPM-Decisions/WeatherService/src/main/resources/lmt_weatherdata_temps_with_missing_data.json
{
    "timeStart": "2021-08-18T22:00:00Z",
    "timeEnd": "2021-08-20T13:00:00Z",
    "interval": 3600,
    "weatherParameters": [
        2001,
        1002
    ],
    "locationWeatherData": [
        {
            "longitude": 9.89166,
            "latitude": 59.76152,
            "altitude": 15.0,
            "data": [
                [
                    0.0,
                    10.75
                ],
                [
                    0.0,
                    9.77
                ],
                [
                    0.0,
                    9.38
                ],
                [
                    0.0,
                    9.07
                ],
                [
                    0.0,
                    7.428
                ],
                [
                    0.0,
                    6.713
                ],
                [
                    0.0,
                    null
                ],
                [
                    0.0,
                    8.07
                ],
                [
                    0.0,
                    11.82
                ],
                [
                    0.0,
                    15.79
                ],
                [
                    0.0,
                    17.93
                ],
                [
                    0.0,
                    19.46
                ],
                [
                    0.0,
                    20.6
                ],
                [
                    0.0,
                    21.77
                ],
                [
                    0.0,
                    22.29
                ],
                [
                    0.0,
                    21.29
                ],
                [
                    0.8,
                    18.9
                ],
                [
                    0.0,
                    17.19
                ],
                [
                    0.0,
                    17.46
                ],
                [
                    null,
                    null
                ],
                [
                    null,
                    null
                ],
                [
                    null,
                    null
                ],
                [
                    0.0,
                    9.95
                ],
                [
                    0.0,
                    10.09
                ],
                [
                    0.0,
                    10.33
                ],
                [
                    0.0,
                    9.38
                ],
                [
                    0.0,
                    8.06
                ],
                [
                    0.0,
                    7.072
                ],
                [
                    0.0,
                    5.752
                ],
                [
                    0.0,
                    5.107
                ],
                [
                    0.0,
                    4.955
                ],
                [
                    0.0,
                    5.675
                ],
                [
                    0.0,
                    8.28
                ],
                [
                    0.0,
                    12.65
                ],
                [
                    0.0,
                    16.25
                ],
                [
                    0.0,
                    18.3
                ],
                [
                    0.0,
                    18.91
                ],
                [
                    0.0,
                    18.7
                ],
                [
                    0.0,
                    19.79
                ],
                [
                    0.0,
                    19.83
                ]
            ],
            "qc":
            [
            	4,
            	4
            ]
            ,
            "length": 40,
            "width": 2
        }
    ]
}

=== H2020-IPM-Decisions/WeatherService/src/test/resources/lmt_weatherdata_missing_lwd.json
{
    "timeStart": "2021-06-25T00:00:00Z",
    "timeEnd": "2021-06-27T23:00:00Z",
    "interval": 3600,
    "weatherParameters": [
        1002,
        2001,
        3002,
        4003
    ],
    "locationWeatherData": [
        {
            "longitude": 10.86952,
            "latitude": 60.70024,
            "altitude": 262.0,
            "data": [
                [14.6,0,64.9,0.1],
                [13.6,0,72.9,0.5],
                [12.6,0,87,0.8],
                [12.4,0,88,0.2],
                [12.3,0,87.5,0.2],
                [12.5,0,84.2,0.5],
                [13,0,80,0.6],
                [13,0,82.6,0.9],
                [12.9,0,86.7,0.5],
                [13.1,0,85.8,1.3],
                [13.3,0,88.7,1.2],
                [14.4,0,82.1,1],
                [14.1,0.2,84.8,0.4],
                [14.6,0.2,86.8,0.7],
                [14.3,0.3,90.3,0.6],
                [14.3,0,91.7,1.2],
                [14.5,0,81.2,1.4],
                [13.2,0,79.3,1.7],
                [12.9,0,82.3,0.9],
                [12.9,0,84.8,0.6],
                [12.8,0,88.4,1.2],
                [12.9,0,89.3,0.3],
                [12.3,0,89.7,1],
                [11.1,0,94.8,0.2],
                [11.5,0,94.4,0.8],
                [11.9,0,90.6,1.2],
                [11.4,0,92.4,0.4],
                [10.9,0,95.9,1],
                [10.8,0,95.4,0.9],
                [11.7,0,92.3,0.5],
                [12.8,0,87.3,0.5],
                [13.2,0,88,1],
                [14,0,83.1,1],
                [15.7,0,75.4,1.3],
                [16.8,0,71.2,0.9],
                [17.3,0,69.4,1.1],
                [16.5,0,74.3,1.2],
                [16.7,0,75.9,1.6],
                [18.2,0,68.3,1],
                [19.2,0,60.9,0.8],
                [19.1,0,59.5,0.5],
                [19.2,0,60.2,0.2],
                [18.3,0,66.4,0.8],
                [17.7,0,71.4,0.8],
                [16.7,0,73.8,0.7],
                [16.1,0,78.7,0.3],
                [16,0,76.5,1.1],
                [15.7,0,61.6,1.9],
                [14.5,0,59.4,1.3],
                [13.2,0,59.7,0.9],
                [12.3,0,64.3,1.5],
                [11.5,0,66.2,1.8],
                [10.9,0,66.4,2.1],
                [10.6,0,66.9,1.7],
                [11.5,0,64.5,1.4],
                [12.2,0,64,2],
                [13.1,0,59.5,2.2],
                [14.2,0,55.1,1.6],
                [15.4,0,52,1],
                [16.8,0,49.9,0.9],
                [17.8,0,47.4,0.7],
                [19,0,42.8,1.1],
                [20,0,40.4,1.8],
                [20.5,0,40.2,1],
                [20.3,0,38.1,3.2],
                [20.4,0,36.1,2.8],
                [20.2,0,36.3,3],
                [19.4,0,38.1,1.7],
                [18.4,0,40.4,0.5],
                [16.7,0,47.8,0.7],
                [15.7,0,50.1,0.6],
                [14.5,0,52.8,0.7]
            ],
            "qc":
            [
            	2,
            	2,
                2,
                2
            ]
            ,
            "length": 72,
            "width": 4
        }
    ]
}

=== H2020-IPM-Decisions/WeatherService/src/test/resources/weatherdata_empty.json
{
  "timeStart": "2020-03-10T00:00:00Z",
  "timeEnd": "2020-03-10T23:00:00Z",
  "interval": 3600,
  "weatherParameters": [],
  "locationWeatherData": [
    {
      "longitude": 14.3711,
      "latitude": 67.2828,
      "altitude": 70,
      "qc": [],
      "data": [[]],
      "length": 0,
      "width": 0
    }
  ]
}

=== H2020-IPM-Decisions/WeatherService/src/main/resources/lwd_testdata_2.json
{"timeStart":"2024-05-31T22:00:00Z","timeEnd":"2024-06-04T22:00:00Z","interval":3600,"weatherParameters":[5001,1001,1901,2001,3001,1002,4003,1003,1004,3002],"locationWeatherData":[{"longitude":11.582,"latitude":59.886,"altitude":0.0,"amalgamation":[0,0,0,0,0,0,0,0,0,0],"data":[[0.0,16.563499450683594,13.363500595092773,0.0,81.3888931274414,14.78,0.357,14.27,15.13,94.1],[0.0,15.613500595092773,13.763500213623047,0.0,88.7536849975586,13.88,0.476,13.11,14.45,95.3],[0.0,13.863500595092773,12.763500213623047,0.0,93.08094787597656,12.86,0.65,12.6,13.1,96.3],[0.0,15.16349983215332,13.263500213623047,0.0,88.42790222167969,12.3,0.632,11.97,12.75,97.1],[0.0,13.863500595092773,12.863500595092773,0.0,93.69204711914062,12.35,0.979,11.89,13.17,97.7],[10.0,14.963500022888184,13.863500595092773,0.0,93.13787841796875,13.65,0.866,13.22,14.56,94.3],[62.0,15.863500595092773,14.213500022888184,0.0,89.9317855834961,15.39,1.372,14.6,16.12,87.3],[146.0,17.9635009765625,14.863500595092773,0.0,82.09674835205078,17.2,1.165,16.11,18.07,80.5],[239.0,20.013500213623047,14.91349983215332,0.0,72.47327423095703,18.61,1.331,18.04,19.26,80.6],[377.0,21.4635009765625,14.613500595092773,0.10000000149011612,65.01472473144531,19.94,1.239,19.28,20.31,68.43],[529.0,22.66349983215332,13.863500595092773,0.20000000298023224,57.56629943847656,20.27,0.726,19.97,20.83,65.99],[605.0,23.613500595092773,13.613500595092773,0.10000000149011612,53.4774169921875,21.09,0.798,20.42,22.24,64.81],[634.0,24.41349983215332,12.763500213623047,0.10000000149011612,48.21882629394531,22.4,1.234,21.99,22.55,61.45],[410.0,23.9635009765625,12.263500213623047,0.10000000149011612,47.93985366821289,23.23,1.599,22.47,23.47,55.54],[336.0,21.41349983215332,14.56350040435791,0.6000000238418579,65.0040054321289,23.9,1.396,23.34,24.72,48.74],[358.0,20.91349983215332,14.213500022888184,0.0,65.53002166748047,24.19,1.441,23.37,24.84,48.77],[318.0,21.66349983215332,13.513500213623047,0.0,59.805328369140625,21.99,1.57,21.15,23.23,59.06],[505.0,23.313499450683594,12.56350040435791,0.0,50.84547424316406,21.44,1.581,21.1,21.72,61.82],[427.0,23.513500213623047,12.06350040435791,0.0,48.61233901977539,21.21,1.286,21.1,21.28,67.84],[300.0,23.16349983215332,12.213500022888184,0.0,50.14274978637695,20.8,0.257,19.72,21.36,71.44],[194.0,22.4635009765625,12.513500213623047,0.0,53.35667419433594,18.37,0.479,17.61,19.53,86.8],[99.0,21.263500213623047,13.66349983215332,0.0,61.88896942138672,16.96,0.56,15.97,17.77,90.7],[26.0,18.66349983215332,13.91349983215332,0.0,73.89112854003906,15.23,0.729,14.46,15.95,94.1],[1.0,16.91349983215332,13.81350040435791,0.0,81.96497344970703,14.09,0.619,13.67,14.48,96.0],[0.0,15.963500022888184,13.763500213623047,0.0,86.78948211669922,13.64,0.554,13.32,13.98,96.9],[0.0,15.013500213623047,13.363500595092773,0.0,89.8686294555664,13.29,0.79,13.05,13.67,97.3],[0.0,15.31350040435791,13.713500022888184,0.0,90.18358612060547,13.16,0.945,12.79,13.46,97.4],[0.0,15.06350040435791,13.963500022888184,0.0,93.14302062988281,13.03,1.369,12.71,13.27,97.6],[0.0,14.81350040435791,13.763500213623047,0.0,93.43315124511719,13.57,1.631,13.17,13.91,95.7],[12.0,14.963500022888184,13.713500022888184,0.0,92.23501586914062,14.29,1.677,13.91,14.75,92.6],[75.0,15.713500022888184,13.863500595092773,0.0,88.76189422607422,14.71,1.502,14.57,14.91,88.8],[172.0,16.9635009765625,13.713500022888184,0.0,81.17665100097656,16.06,1.509,14.87,16.62,83.2],[263.0,18.263500213623047,13.463500022888184,0.0,73.5821533203125,17.71,1.723,16.66,18.45,77.48],[405.0,20.013500213623047,13.113500595092773,0.0,64.49107360839844,18.89,1.898,18.48,19.49,72.27],[536.0,21.41349983215332,12.963500022888184,0.0,58.587520599365234,19.89,1.531,19.46,20.58,68.25],[615.0,22.363500595092773,12.91349983215332,0.0,55.1068229675293,21.04,1.344,20.37,21.8,65.19],[698.0,23.263500213623047,12.263500213623047,0.0,50.00475311279297,22.2,1.586,21.56,22.56,59.73],[688.0,23.66349983215332,11.81350040435791,0.0,47.38792419433594,22.88,1.251,22.42,23.53,56.02],[648.0,24.063499450683594,11.763500213623047,0.0,46.109397888183594,23.09,1.265,22.26,24.17,53.15],[680.0,23.9635009765625,12.41349983215332,0.0,48.41449737548828,24.13,0.998,23.55,24.76,47.89],[660.0,24.41349983215332,11.91349983215332,0.0,45.60059356689453,24.28,0.824,23.74,24.68,45.04],[560.0,24.513500213623047,11.81350040435791,0.0,45.03059005737305,24.68,0.733,24.26,25.61,43.81],[443.0,24.2135009765625,11.713500022888184,0.0,45.545692443847656,24.36,0.932,23.85,24.99,45.34],[325.0,23.66349983215332,11.613500595092773,0.0,46.7664794921875,24.36,1.643,23.91,24.77,45.24],[198.0,23.063499450683594,11.613500595092773,0.0,48.49113082885742,22.77,0.919,20.16,23.9,53.69],[95.0,21.4635009765625,12.763500213623047,0.0,57.649253845214844,18.53,0.443,17.94,20.09,76.91],[28.0,19.863500595092773,13.66349983215332,0.0,67.46755981445312,19.39,0.994,18.05,19.89,70.08],[1.0,18.763500213623047,14.31350040435791,0.0,75.3581314086914,17.05,0.452,16.26,19.26,80.6],[0.0,17.91349983215332,14.91349983215332,0.0,82.62088012695312,16.25,0.409,15.61,17.0,83.8],[0.0,17.113500595092773,14.963500022888184,0.0,87.1785888671875,16.98,0.859,16.03,17.32,80.5],[0.0,16.363500595092773,14.463500022888184,0.0,88.5287094116211,16.54,0.946,16.05,16.73,83.7],[0.0,16.16349983215332,14.66349983215332,0.0,90.8290023803711,16.0,0.761,15.57,16.59,87.7],[0.0,16.063499450683594,14.763500213623047,0.0,92.00144958496094,15.3,0.547,14.89,15.64,91.4],[8.0,16.113500595092773,15.06350040435791,0.0,93.49681854248047,15.32,0.414,15.1,15.59,93.5],[46.0,16.9635009765625,15.363500595092773,0.0,90.30191040039062,15.81,0.615,15.59,16.07,91.8],[82.0,17.763500213623047,14.763500213623047,0.0,82.60262298583984,16.53,1.081,16.02,16.95,85.7],[82.0,17.9635009765625,14.31350040435791,0.0,79.2337417602539,17.25,1.093,16.91,17.62,76.91],[247.0,19.563499450683594,12.66349983215332,0.0,64.3927993774414,17.78,1.174,17.52,17.95,70.22],[232.0,19.91349983215332,11.963500022888184,0.0,60.177852630615234,18.28,1.48,17.9,19.03,66.09],[163.0,19.4635009765625,11.463500022888184,0.0,59.873165130615234,19.0,1.862,18.71,19.62,55.9],[328.0,20.363500595092773,10.363500595092773,0.0,52.636512756347656,20.07,2.608,19.46,20.71,52.42],[416.0,20.863500595092773,9.463500022888184,0.0,48.0550422668457,21.39,2.98,20.68,21.75,46.87],[579.0,21.863500595092773,8.513500213623047,0.0,42.39398956298828,21.95,3.003,21.58,22.29,42.21],[722.0,22.66349983215332,7.113500118255615,0.0,36.70887756347656,21.56,3.494,21.01,22.1,45.66],[572.0,22.313499450683594,7.06350040435791,0.0,37.36967468261719,21.94,3.754,21.26,22.63,42.83],[444.0,21.813499450683594,7.213500022888184,0.0,38.92359924316406,21.83,4.187,21.31,22.29,44.43],[350.0,21.613500595092773,7.06350040435791,0.0,38.999820709228516,21.99,3.669,21.34,22.56,39.4],[313.0,21.41349983215332,6.4135003089904785,0.0,37.75695037841797,20.87,2.71,19.43,22.15,31.5],[211.0,20.9635009765625,4.613500118255615,0.0,34.25971984863281,18.46,1.84,17.7,19.43,35.65],[108.0,18.91349983215332,3.9135000705718994,0.0,37.03708267211914,16.21,1.044,15.34,17.61,40.18],[35.0,16.66349983215332,3.4635000228881836,0.0,41.344017028808594,15.05,1.847,14.48,15.32,40.91],[1.0,15.06350040435791,3.363499879837036,0.0,45.473209381103516,13.73,0.679,13.19,14.49,45.34],[0.0,14.013500213623047,3.0134999752044678,0.0,47.47422409057617,12.07,1.243,10.46,13.27,52.56],[0.0,13.31350040435791,2.3635001182556152,0.0,47.445350646972656,11.6,0.749,9.11,13.02,50.36],[0.0,12.56350040435791,2.063499927520752,0.0,48.77626419067383,7.203,0.601,6.184,8.74,75.04],[0.0,10.41349983215332,6.1635003089904785,0.0,74.95870971679688,7.371,0.486,6.216,9.37,75.53],[0.0,9.963500022888184,5.863500118255615,0.0,75.66230010986328,6.112,0.202,5.319,6.658,83.9],[15.0,9.91349983215332,5.513500213623047,0.0,74.09830474853516,8.55,1.15,6.753,9.5,73.69],[84.0,10.963500022888184,5.4135003089904785,0.0,68.61103057861328,10.62,1.945,9.49,11.39,66.19],[192.0,12.16349983215332,5.4135003089904785,0.0,63.380455017089844,12.48,2.132,11.4,13.27,57.14],[319.0,13.41349983215332,4.513500213623047,0.0,54.85326385498047,13.13,2.383,12.83,13.58,54.1],[443.0,14.613500595092773,3.1635000705718994,0.0,46.154178619384766,14.2,2.994,13.59,15.01,50.47],[568.0,15.713500022888184,2.563499927520752,0.0,41.21517562866211,15.25,3.158,14.77,15.8,47.66],[618.0,16.613500595092773,2.613499879837036,0.0,39.055179595947266,15.84,3.336,15.36,16.36,47.64],[712.0,18.363500595092773,1.9135000705718994,0.0,33.27150344848633,16.67,4.151,16.06,17.19,50.41],[598.0,16.613500595092773,7.113500118255615,0.0,53.44525146484375,16.97,4.754,16.28,17.46,50.54],[422.0,17.013500213623047,5.9135003089904785,0.0,47.97800064086914,16.51,4.397,15.95,17.14,55.14],[444.0,17.063499450683594,6.963500022888184,0.0,51.41048049926758,16.51,4.57,16.27,16.79,56.02],[413.0,17.063499450683594,7.613500118255615,0.0,53.74628448486328,16.55,4.972,16.06,17.03,57.79],[281.0,16.063499450683594,8.41349983215332,0.0,60.4735221862793,15.97,4.428,15.45,16.38,60.89],[261.0,15.91349983215332,8.763500213623047,0.0,62.51839065551758,16.36,4.603,15.97,16.91,57.96],[250.0,16.16349983215332,8.763500213623047,0.0,61.528846740722656,15.72,4.36,15.16,16.3,61.01],[128.0,14.363500595092773,10.213500022888184,0.10000000149011612,76.13211822509766,14.82,3.377,14.43,15.11,66.84],[52.0,14.06350040435791,10.213500022888184,0.10000000149011612,77.62489318847656,14.49,2.209,14.21,14.65,67.46],[30.0,13.713500022888184,9.56350040435791,0.0,76.02607727050781,14.43,1.943,14.24,14.68,66.94],[1.0,13.513500213623047,8.16349983215332,0.0,70.07555389404297,14.03,2.386,13.44,14.68,69.37],[0.0,13.16349983215332,7.6635003089904785,0.10000000149011612,69.29512786865234,13.31,2.128,13.19,13.46,73.69]],"qc":[2,2,2,2,2,2,2,2,2,2],"width":10,"length":97}]}
